### PR TITLE
thirdparty: added e2k support (MCST Elbrus 2000)

### PR DESCRIPTION
**Pull request by r-a-sattarov**
Added e2k support in telemetry and protobuf-2.5.0.

### CODE REVIEW

**Comment by r-a-sattarov** [comment]
@LWSS

Kisak-Strike compiles without errors in client version and dedicated. There is a problem on "Create release" stage (**Error: Resource not accessible by integration**).

**Comment by LWSS** [comment]
this is cool, thanks. I can't say I have a Moscow CPU, but I trust your changes because I saw you in rbdoom3bfg as well :P

**Comment by r-a-sattarov** [comment]
> I can't say I have a Moscow CPU

If you are interested, I can try to help you get free ssh access to server on e2k CPU. Send me an email (address in my profile).

> I saw you in rbdoom3bfg as well :P

I also ported OpenXRay on e2k 🙂 (it's an open source game engine for the S.T.A.L.K.E.R.).

**Comment by LWSS** [comment]
Thanks, but I'm not sure what I'd do on it. They are pretty neat though, seems like they're only available in Russia? http://www.ineum.ru/elbrus_801-pc_gen4
I had my friend find this link lol, he says you're probably associated with them in someway because they're big money $$

Yeah also, if you're on a game-spree - there's also Counter-strike: source offensive, it's basically counter-strike source Open-Source. It's pretty popular in Russia, maybe you've heard of it.

**Comment by r-a-sattarov** [comment]
> seems like they're only available in Russia?

Yes, they are available so far only in Russia. You can buy them through this store - https://imaxai.ru/
But I hope that soon it will be possible for foreigners to buy.

> you're probably associated with them in someway

I have the opportunity to work with them live 🙂 

> Yeah also, if you're on a game-spree - there's also Counter-strike: source offensive, it's basically counter-strike source Open-Source. It's pretty popular in Russia, maybe you've heard of it.

Thanks, I haven't heard of this game before.

**Pull request merged**
