### PR TITLE
Automatize builds with GitHub Actions

### PR DESCRIPTION
**Pull request by PANCHO7532B**
So i thought this would be a nice thing to have since often people can have _some_ problems while building or lack of disk space to build (like me xd)
And also for those who just want to peek through

I set this one to compile both client and dedicated using RocketUI and your Physics engine by default, average build time: 1h 20min only client - almost 2hrs for both client and dedicated using two cores

Once built, client and dedicated binaries are zipped and published into the release section of the repository allowing anyone to download it automatically. Additional files from Kisak-Strike-Files are automatically included too.
It generates a new release every push/pull request, also you can initiate it manually from the Actions Panel.

Probably it might need some tweaks so feel free to check my fork and generated releases if it looks good so i can make further fixes if you want to merge this out soon-ish

### CODE REVIEW

**Comment by LWSS** [comment]
hmmmm I would prefer people to build it on their own machines, but I understand that the average gamer doesn't really want to do that... 

Sure we can try it, but I'll think of it more as a demo-experience

**Comment by LWSS** [comment]
`Unable to enable Actions for this repository.`

grug, github not working right

**Comment by PANCHO7532B** [comment]
> `Unable to enable Actions for this repository.`
> 
> grug, github not working right

Yeah GitHub sometimes is weird
Go to Repository Settings > Actions and check "Allow All Actions" 

Then go to the Actions tab, click on CI-Workflow on the "Workflows" list in your left and click on "Run Workflow"
image

If still doesn't works, commit a new-line in .github/workflows/kstrike-compile.yml and should be ready to go xd

**Comment by LWSS** [comment]
here i'll just invite u to the group so u can edit it lol

**Comment by PANCHO7532B** [comment]
Hey there @LWSS, was working close with GitHub and seems like the reason for Actions not working properly is that @kaonashiHF (an org member) has it's GitHub account banned as spam and Actions refuse to start workflows because of that... If you don't mind, could you remove the user from the org so i could verify? xd
Below i'm attaching relevant screenshot of GitHub support

image

**Comment by LWSS** [comment]
> Hey there @LWSS, was working close with GitHub and seems like the reason for Actions not working properly is that @kaonashiHF (an org member) has it's GitHub account banned as spam and Actions refuse to start workflows because of that... If you don't mind, could you remove the user from the org so i could verify? xd Below i'm attaching relevant screenshot of GitHub support
> 
> image

ah right that account's been dead for like 5 years(not mine), I removed it

**Pull request merged**
